# Generated by Django 4.2.3 on 2023-10-11 05:03

import championship.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('state', models.BooleanField(default=True)),
                ('categorys', models.ManyToManyField(to='championship.category')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[championship.validators.validate_str])),
                ('surnames', models.CharField(max_length=30, validators=[championship.validators.validate_str])),
                ('dni', models.PositiveIntegerField(validators=[championship.validators.validate_dni])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('birthdate', models.DateField()),
                ('department', models.IntegerField(choices=[(1, 'Amazonas'), (2, 'Ancash'), (3, 'Apurimac'), (4, 'Arequipa'), (5, 'Ayacucho'), (6, 'Cajamarca'), (7, 'Callao'), (8, 'Cusco'), (9, 'Huancavelica'), (10, 'Huanuco'), (11, 'Ica'), (12, 'Junín'), (13, 'La Libertad'), (14, 'Lambayeque'), (15, 'Lima'), (16, 'Loreto'), (17, 'Madre de Dios'), (18, 'Moquegua'), (19, 'Pasco'), (20, 'Piura'), (21, 'Puno'), (22, 'San Martín'), (23, 'Tacna'), (24, 'Tumbes'), (25, 'Ucayali')], default=4)),
                ('province', models.CharField(max_length=30, validators=[championship.validators.validate_str])),
                ('profession', models.CharField(blank=True, max_length=30, validators=[championship.validators.validate_str])),
                ('activity', models.CharField(blank=True, max_length=30, validators=[championship.validators.validate_str])),
                ('degree_instruction', models.CharField(blank=True, max_length=30, validators=[championship.validators.validate_str])),
                ('civil_status', models.CharField(blank=True, max_length=50, validators=[championship.validators.validate_str])),
                ('military_card', models.PositiveIntegerField(null=True, unique=True, validators=[championship.validators.validate_phone])),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField(validators=[championship.validators.validate_phone])),
                ('num_promotion', models.PositiveIntegerField()),
                ('promotion_delegate', models.BooleanField(default=False)),
                ('promotion_sub_delegate', models.BooleanField(default=False)),
                ('partner', models.BooleanField(default=False)),
                ('NSA_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('Persons', models.ManyToManyField(to='championship.person')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('team1_goals', models.IntegerField(default=0)),
                ('team2_goals', models.IntegerField(default=0)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.championship')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='championship.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='championship.team')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(to='championship.team'),
        ),
    ]
