# Generated by Django 4.2.3 on 2023-12-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='team_delegate',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False),
        ),
    ]
