# Generated by Django 4.2.3 on 2023-12-29 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="team1_goals",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(limit_value=50)],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="team2_goals",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(limit_value=50)],
            ),
        ),
    ]
