# Generated by Django 4.2.3 on 2024-01-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="state",
            field=models.BooleanField(default=True),
        ),
    ]
