# Generated by Django 4.2.3 on 2023-11-18 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.RemoveField(
            model_name="person",
            name="num_promotion",
        ),
    ]
