# Generated by Django 4.2.3 on 2023-10-23 16:56

import championship.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.PositiveIntegerField(unique=True, validators=[championship.validators.validate_dni]),
        ),
        migrations.AlterField(
            model_name='person',
            name='month_promotion',
            field=models.CharField(blank=True, max_length=15, validators=[championship.validators.validate_month]),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_promotion',
            field=models.PositiveIntegerField(validators=[championship.validators.validate_year]),
        ),
    ]
