# Generated by Django 4.2.3 on 2023-11-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dicipline',
            new_name='Discipline',
        ),
    ]
