# Generated by Django 4.2.3 on 2024-01-09 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Fecha del Anuncio')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.championship')),
            ],
        ),
    ]
