# Generated by Django 4.2.3 on 2023-11-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='state',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='partner',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='promotion_delegate',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='promotion_sub_delegate',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=True),
        ),
    ]
