# Generated by Django 4.2.3 on 2023-11-18 00:20

import championship.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=30, validators=[championship.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=30, validators=[championship.validators.validate_str]),
        ),
    ]
