# Generated by Django 4.2.3 on 2023-10-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
