# Generated by Django 4.2.3 on 2024-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
