# Generated by Django 4.2.3 on 2023-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_person_image_alter_person_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_jale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
