# Generated by Django 4.2.3 on 2024-01-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_anuncio_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
