# Generated by Django 4.2.3 on 2024-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("championship", "0003_alter_game_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="sum_team_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
