# Generated by Django 4.2.3 on 2023-10-26 21:35

import championship.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_person_is_jale_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_card',
            field=models.PositiveIntegerField(blank=True, unique=True, validators=[championship.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='person',
            name='month_promotion',
            field=models.CharField(max_length=15, validators=[championship.validators.validate_month]),
        ),
        migrations.AlterField(
            model_name='person',
            name='num_promotion',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.PositiveIntegerField(blank=True, validators=[championship.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(blank=True, max_length=30, validators=[championship.validators.validate_str]),
        ),
    ]
