# Generated by Django 4.2.3 on 2023-10-26 21:36

import championship.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_alter_person_address_alter_person_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='military_card',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[championship.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[championship.validators.validate_phone]),
        ),
    ]
