# Generated by Django 4.2.3 on 2023-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0005_alter_person_military_card_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='NSA_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='num_promotion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
