# Generated by Django 4.2.3 on 2023-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0006_alter_person_nsa_code_alter_person_num_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
