# Generated by Django 4.2.3 on 2023-07-22 13:21

from django.db import migrations, models
import partner.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, validators=[partner.validators.validate_str]
                    ),
                ),
                (
                    "surnames",
                    models.CharField(
                        max_length=100, validators=[partner.validators.validate_str]
                    ),
                ),
                ("num_carnet", models.PositiveIntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[partner.validators.validate_str],
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[partner.validators.validate_str],
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[partner.validators.validate_str],
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[partner.validators.validate_str],
                    ),
                ),
                (
                    "degree_instruction",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[partner.validators.validate_str],
                    ),
                ),
                ("civil_status", models.CharField(blank=True, max_length=50)),
                ("military_card", models.PositiveIntegerField(null=True, unique=True)),
                (
                    "dni",
                    models.PositiveIntegerField(
                        unique=True, validators=[partner.validators.validate_dni]
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "phone",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[partner.validators.validate_phone],
                    ),
                ),
                ("num_promotion", models.PositiveIntegerField()),
                ("promotion_delegate", models.BooleanField(default=False)),
                ("NSA_code", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
