# Generated by Django 4.2.3 on 2023-07-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="NSA_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="activity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="civil_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="date_created",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="degree_instruction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="department",
            field=models.CharField(
                choices=[
                    ("AM", "Amazonas"),
                    ("AN", "Ancash"),
                    ("AP", "Apurimac"),
                    ("AR", "Arequipa"),
                    ("AY", "Ayacucho"),
                    ("CA", "Cajamarca"),
                    ("CL", "Callao"),
                    ("CU", "Cusco"),
                    ("HU", "Huancavelica"),
                    ("HA", "Huanuco"),
                    ("IC", "Ica"),
                    ("JU", "Junín"),
                    ("LL", "La Libertad"),
                    ("LA", "Lambayeque"),
                    ("LI", "Lima"),
                    ("LO", "Loreto"),
                    ("MD", "Madre de Dios"),
                    ("MO", "Moquegua"),
                    ("PA", "Pasco"),
                    ("PI", "Piura"),
                    ("PU", "Puno"),
                    ("SM", "San Martín"),
                    ("TA", "Tacna"),
                    ("TU", "Tumbes"),
                    ("UC", "Ucayali"),
                ],
                default="Arequipa",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="military_card",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="num_carnet",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="num_promotion",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="promotion_delegate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="dni",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
