# Generated by Django 4.2.3 on 2023-07-25 19:21

from django.db import migrations, models
import partner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='activity',
            field=models.CharField(blank=True, max_length=30, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='civil_status',
            field=models.CharField(blank=True, max_length=50, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='degree_instruction',
            field=models.CharField(blank=True, max_length=30, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='department',
            field=models.CharField(blank=True, max_length=30, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='partner',
            name='military_card',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[partner.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=30, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='num_carnet',
            field=models.PositiveIntegerField(validators=[partner.validators.validate_dni]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='profession',
            field=models.CharField(blank=True, max_length=30, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='province',
            field=models.CharField(blank=True, max_length=30, validators=[partner.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='surnames',
            field=models.CharField(max_length=30, validators=[partner.validators.validate_str]),
        ),
    ]
