# Generated by Django 4.2.3 on 2023-07-18 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0002_partner_nsa_code_partner_activity_partner_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="user",
        ),
    ]
