# Generated by Django 4.2.3 on 2023-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partner_activity_alter_partner_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='department',
            field=models.IntegerField(choices=[(1, 'Amazonas'), (2, 'Ancash'), (3, 'Apurimac'), (4, 'Arequipa'), (5, 'Ayacucho'), (6, 'Cajamarca'), (7, 'Callao'), (8, 'Cusco'), (9, 'Huancavelica'), (10, 'Huanuco'), (11, 'Ica'), (12, 'Junín'), (13, 'La Libertad'), (14, 'Lambayeque'), (15, 'Lima'), (16, 'Loreto'), (17, 'Madre de Dios'), (18, 'Moquegua'), (19, 'Pasco'), (20, 'Piura'), (21, 'Puno'), (22, 'San Martín'), (23, 'Tacna'), (24, 'Tumbes'), (25, 'Ucayali')], default=4),
        ),
    ]
